#!/usr/bin/python

#1. print out numbers in one line
print "numbers in one line"
n = 10
i = 1
line = ''
while i<=n:
    line = line + str(i)+'\t'
    i += 1
print line

#2. print out a reverse triangle
print "reverse triangle"

total_rows = 10
current_row = 1

while current_row <= total_rows:
	number_of_spaces = current_row - 1
	number_of_stars = total_rows - number_of_spaces
	# store all spaces for the current row
	spaces = ''
	i = 1
	while i <= number_of_spaces:
		spaces = spaces + ' '
		i = i + 1
	# store all stars for the current row
	stars = ''
	j = 1
	while j <= number_of_stars:
		stars = stars + '*'
		j = j + 1

	line = spaces + stars # line is the variable for all characters for the current row
	print line

	current_row = current_row + 1

##################################

#3. print a pyramid: the number of stars for ith row
#   is 2*i - 1
print "Pyramid"
number_of_rows = 10

current_row = 1
while current_row <= number_of_rows:
	number_of_stars = 2*current_row - 1
	number_of_spaces = number_of_rows - current_row
	# store all spaces for the current row
	spaces = ''
	i = 1
	while i <= number_of_spaces:
		spaces += ' '
		i += 1

	# store all stars for the current row
	stars = ''
	k = 1
	while k <= number_of_stars:
		stars += '*'
		k += 1

	line = spaces + stars
	print line

	current_row += 1

##############################
#4. print out a diamond
print "diamond with height 7 (for half)"
height = 7 # the height of the above half traingle

# print the above half
current_row = 1
while current_row <= height:
	number_of_stars = 2*current_row - 1
	number_of_spaces = height - current_row
	# store all spaces for the current row
	spaces = ''
	i = 1
	while i <= number_of_spaces:
		spaces += ' '
		i += 1
	
	# store all stars for the current row
	stars = ''
	k = 1
	while k <= number_of_stars:
		stars += '*'
		k += 1

	line = spaces + stars
	print line

	current_row += 1

# print the below half
current_row = 1
while current_row <= height-1:
	number_of_stars = 2*(height-current_row) - 1
	number_of_spaces = current_row
	# store spaces for the 'current' row
	spaces = ''
	i = 1
	while i <= number_of_spaces:
		spaces += ' '
		i += 1
	#store stars for the 'current' row
	stars = ''
	k = 1
	while k <= number_of_stars:
		stars += '*'
		k += 1

	line = spaces + stars
	print line

	current_row += 1
##############################
#5. print out a chess board
#   To run this code, you need to install Python Image Library: PIL:http://www.pythonware.com/products/pil/
#   To install a package, please take a look at this: http://www.wikihow.com/Install-Python-Packages-on-Windows-7
from PIL import Image
from PIL import ImageDraw

print "chess board: chess_board.png is then in the folder same as this file"
size = 8 
square_width = 50
chess_width = square_width*size

board = Image.new('L', (chess_width, chess_width))
draw_board = ImageDraw.Draw(board).rectangle

row  = 1 # current row
while row <= size:
	col = 1 # current column
	while col <= size:
		x1 = (col-1)*square_width
		y1 = (row-1)*square_width
		x2 = x1 + square_width
		y2 = y1 + square_width
		coordinate = (x1,y1,x2,y2)
		
		if (row+col) % 2 == 0: # if row+col is even, print out a white square
			draw_board(coordinate,fill='white')
		else: # row+col is odd, print out a black square
			draw_board(coordinate,fill='black')

		col += 1

	row += 1
board.save('chess_board.png')

###############################
#6. game: guess number
import random

print "Guess an integer number randomly generated by computer"
answer = raw_input('Do you want to play this game (Y/N)? ')

while answer == 'Y' or answer == 'y':
	times_used = 0
	number = random.randint(1, 100000)
	print "Number is generated..."
	while True:
		guess = raw_input("what's your guess? ")
		guess = int(guess)
		if guess < number:
			print "Please try a larger number"
			times_used += 1
		elif guess > number:
			print "Please try a smaller number"
			times_used += 1
		else:
			print "Bingo!"
			break

	print 'You guess',times_used,'times'
	if times_used < 10:
		print "Wonderful job..."
	elif times_used < 20:
		print "Good job..."
	else:
		print "Try to do better next time..."

	answer = raw_input('Do you want to play this game again (Y/N)? ')

print "Goodbye"
